// packages/x6-react-shape/src/registry.ts
import React from 'react'
import { Graph, Node } from '@antv/x6'
import { ReactShape } from './node'

export interface ReactShapeComponentProps {
  node: Node
  graph: Graph
}

export type ReactShapeComponent =
  | React.ComponentType<ReactShapeComponentProps>
  | React.ReactElement

export type EffectKeys = ReadonlyArray<string>

export interface ReactNodeOptions {
  width?: number
  height?: number
  primer?: ReactShape.Primer
  attrs?: ReactShape.Attributes
}

export interface ReactShapeConfig extends ReactNodeOptions {
  shape: string
  component: ReactShapeComponent
  effect?: EffectKeys
  inherit?: string
  [key: string]: unknown
}

export const shapeMaps: Record<
  string,
  {
    component: ReactShapeComponent
    effect?: EffectKeys
  }
> = {}

export function register(config: ReactShapeConfig) {
  const { shape, component, effect, inherit, ...others } = config
  if (!shape) {
    throw new Error('should specify shape in config')
  }
  shapeMaps[shape] = {
    component,
    effect,
  }

  Graph.registerNode(
    shape,
    {
      inherit: inherit || 'react-shape',
      ...(others as ReactNodeOptions),
    },
    true,
  )
}

// packages/x6-angular-shape/src/registry.ts
import { Injector, TemplateRef, Type } from '@angular/core'
import { Graph } from '@antv/x6'
import { AngularShape } from './node'

export type Content = TemplateRef<unknown> | Type<unknown>

export interface AngularNodeOptions {
  width?: number
  height?: number
  primer?: AngularShape.Primer
  attrs?: AngularShape.Attributes
  markup?: AngularShape.MarkupNode[]
}

export interface AngularShapeConfig extends AngularNodeOptions {
  shape: string
  injector: Injector
  content: Content
  inherit?: string
  [key: string]: unknown
}

export const registerInfo: Map<
  string,
  {
    injector: Injector
    content: Content
  }
> = new Map()

export function register(config: AngularShapeConfig) {
  const { shape, injector, content, inherit, ...others } = config
  registerInfo.set(shape, { injector, content })

  Graph.registerNode(
    shape,
    {
      inherit: inherit || 'angular-shape',
      ...(others as AngularNodeOptions),
    },
    true,
  )
}
