// packages/x6-react-shape/src/view.ts
import React, { ReactPortal } from 'react'
import { createPortal } from 'react-dom'
import { createRoot, Root } from 'react-dom/client'
import { Dom, NodeView, Node } from '@antv/x6'
import {
  isActive as portalIsActive,
  connect as portalConnect,
  disconnect as portalDisconnect,
} from './portal'
import { Wrap } from './wrap'

export class ReactShapeView extends NodeView<Node> {
  static action = 'react' as any
  root?: Root

  protected targetId() {
    return `${this.graph.view.cid}:${this.cell.id}`
  }

  getComponentContainer() {
    return this.selectors && (this.selectors.foContent as HTMLDivElement)
  }

  confirmUpdate(flag: number) {
    const ret = super.confirmUpdate(flag)
    return this.handleAction(ret, ReactShapeView.action, () => {
      this.renderReactComponent()
    })
  }

  protected renderReactComponent() {
    this.unmountReactComponent()
    const container = this.getComponentContainer()
    const node = this.cell

    if (container) {
      const elem = React.createElement(Wrap, { node, graph: this.graph })
      if (portalIsActive()) {
        const portal = createPortal(elem, container, node.id) as ReactPortal
        portalConnect(this.targetId(), portal)
      } else {
        this.root = createRoot(container)
        this.root.render(elem)
      }
    }
  }

  protected unmountReactComponent() {
    const container = this.getComponentContainer()
    if (container && this.root) {
      this.root.unmount()
      this.root = undefined
    }
  }

  onMouseDown(e: Dom.MouseDownEvent, x: number, y: number) {
    const target = e.target as Element
    const tagName = target.tagName.toLowerCase()
    if (tagName === 'input') {
      const type = target.getAttribute('type')
      if (
        type == null ||
        [
          'text',
          'password',
          'number',
          'email',
          'search',
          'tel',
          'url',
        ].includes(type)
      ) {
        return
      }
    }

    super.onMouseDown(e, x, y)
  }

  unmount() {
    if (portalIsActive()) {
      portalDisconnect(this.targetId())
    }
    this.unmountReactComponent()
    super.unmount()
    return this
  }
}

ReactShapeView.config({
  bootstrap: [ReactShapeView.action],
  actions: {
    component: ReactShapeView.action,
  },
})

NodeView.registry.register('react-shape-view', ReactShapeView, true)

// packages/x6-angular-shape/src/view.ts
import {
  ComponentRef,
  EmbeddedViewRef,
  TemplateRef,
  ViewContainerRef,
} from '@angular/core'
import { Dom, NodeView, Node } from '@antv/x6'
import { Content, registerInfo } from './registry'

export class AngularShapeView extends NodeView<Node> {
  static action = 'angular' as any
  getNodeContainer(): HTMLDivElement {
    return this.selectors && (this.selectors.foContent as HTMLDivElement)
  }

  override confirmUpdate(flag: number): number {
    const ret = super.confirmUpdate(flag)
    return this.handleAction(ret, AngularShapeView.action, () =>
      this.renderAngularContent(),
    )
  }

  private getNgArguments(): Record<string, any> {
    const input = (this.cell.data?.ngArguments as Record<string, any>) || {}
    return input
  }

  /** 当执行 node.setData() 时需要对实例设置新的输入值 */
  private setInstanceInput(
    content: Content,
    ref: EmbeddedViewRef<any> | ComponentRef<any>,
  ): void {
    const ngArguments = this.getNgArguments()
    if (content instanceof TemplateRef) {
      const embeddedViewRef = ref as EmbeddedViewRef<any>
      embeddedViewRef.context = { ngArguments }
    } else {
      const componentRef = ref as ComponentRef<any>
      Object.keys(ngArguments).forEach((v) =>
        componentRef.setInput(v, ngArguments[v]),
      )
      componentRef.changeDetectorRef.detectChanges()
    }
  }

  protected renderAngularContent(): void {
    const container = this.getNodeContainer()
    if (container) {
      this.unmountAngularContent()
      const node = this.cell
      const { injector, content } = registerInfo.get(node.shape)!
      const viewContainerRef = injector.get(ViewContainerRef)
      if (content instanceof TemplateRef) {
        const ngArguments = this.getNgArguments()
        const embeddedViewRef = viewContainerRef.createEmbeddedView(content, {
          ngArguments,
        })
        embeddedViewRef.rootNodes.forEach((node) => container.appendChild(node))
        embeddedViewRef.detectChanges()
        node.on('change:data', () =>
          this.setInstanceInput(content, embeddedViewRef),
        )
      } else {
        const componentRef = viewContainerRef.createComponent(content, {
          injector,
        })
        const insertNode = (componentRef.hostView as EmbeddedViewRef<any>)
          .rootNodes[0] as HTMLElement
        container.appendChild(insertNode)
        this.setInstanceInput(content, componentRef)
        node.on('change:data', () =>
          this.setInstanceInput(content, componentRef),
        )
        node.on('removed', () => componentRef.destroy())
      }
    }
  }

  protected unmountAngularContent(): HTMLDivElement {
    const container = this.getNodeContainer()
    container.innerHTML = ''
    return container
  }

  override onMouseDown(e: Dom.MouseDownEvent, x: number, y: number) {
    const target = e.target as Element
    const tagName = target.tagName.toLowerCase()
    if (tagName === 'input') {
      const type = target.getAttribute('type')
      if (
        type == null ||
        [
          'text',
          'password',
          'number',
          'email',
          'search',
          'tel',
          'url',
        ].includes(type)
      ) {
        return
      }
    }

    super.onMouseDown(e, x, y)
  }

  override unmount(): this {
    this.unmountAngularContent()
    super.unmount()
    return this
  }
}

AngularShapeView.config({
  bootstrap: [AngularShapeView.action],
  actions: {
    component: AngularShapeView.action,
  },
})

NodeView.registry.register('angular-shape-view', AngularShapeView, true)
